@startuml Create Notification Content & Message
skinparam shadowing true
skinparam sequence {
	ParticipantBackgroundColor LightYellow
	ParticipantBorderColor red
}
Title: Create Notification Content & Message
actor "Admin" as User1
participant "Backoffice" as Frontend
participant "Microservice" as Microservice
participant "MSSQL" as Database

User1 -> Frontend: Create Notification

Frontend -> Microservice: POST /notification

Microservice -> Microservice: Check notification type \n content and message

Microservice -> Database: Save Notification

alt Success

Database --> Microservice: Return notification data

Microservice --> Frontend: Return notification data

Frontend --> User1: Return notification data

else #LightYellow

Database --> Microservice: Return error

Microservice --> Frontend: Return error

Frontend --> User1: Return error

end

@enduml