@startuml Frontend Get List Banner
skinparam shadowing true
skinparam sequence {
	ParticipantBackgroundColor LightYellow
	ParticipantBorderColor red
}
Title: Frontend Get List Banner
actor "Admin" as User1
participant "Frontend" as Frontend
participant "Microservice" as Microservice
participant "MSSQL" as Database

User1 -> Frontend: Get banner by id

Frontend -> Microservice: GET /v1/landingpage/banners

Microservice -> Database: Get list 3 banner data

alt Success

Database --> Microservice: Return list banner data

Microservice --> Frontend: Return list banner data

Frontend --> User1: Return list banner data

else #LightYellow

Database --> Microservice: Return error message

Microservice --> Frontend: Return error message

Frontend --> User1: Return error message

end

@enduml