@startuml Admin Get List Banner
skinparam shadowing true
skinparam sequence {
	ParticipantBackgroundColor LightYellow
	ParticipantBorderColor red
}
Title: Admin Get List Banner
actor "Admin" as User1
participant "Backoffice" as Frontend
participant "Microservice" as Microservice
participant "MSSQL" as Database

User1 -> Frontend: Get banner by id

Frontend -> Microservice: GET /v1/banners

Microservice -> Database: Get list banner data

alt Success

Database --> Microservice: Return list banner data \nand pagination data

Microservice --> Frontend: Return list banner data \nand pagination data

Frontend --> User1: Return list banner data \nand pagination data

else #LightYellow

Database --> Microservice: Return error message

Microservice --> Frontend: Return error message

Frontend --> User1: Return error message

end

@enduml