@startuml Delete Notification
skinparam shadowing true
skinparam sequence {
	ParticipantBackgroundColor LightYellow
	ParticipantBorderColor red
}
Title: Delete Notification
actor "Admin" as User1
participant "Backoffice" as Frontend
participant "Microservice" as Microservice
participant "MSSQL" as Database

User1 -> Frontend: Delete Notification

Frontend -> Microservice: DELETE /notification/:id

Microservice -> Database: Delete Notification

alt success

Database --> Microservice: Return success

Microservice --> Frontend: Return success

Frontend --> User1: Return success

else #LightYellow

Database --> Microservice: Return error

Microservice --> Frontend: Return error

Frontend --> User1: Return error

end

@enduml