@startuml Admin Get Notification
skinparam shadowing true
skinparam sequence {
	ParticipantBackgroundColor LightYellow
	ParticipantBorderColor red
}
Title: Admin Get Notification
actor "Admin" as User1
participant "Backoffice" as Frontend
participant "Microservice" as Microservice
participant "MSSQL" as Database

User1 -> Frontend: Get Notification

Frontend -> Microservice: GET /v1/notification/:id

Microservice -> Database: Get Notification

Database --> Microservice: Return notification data

Microservice --> Frontend: Return notification data

Frontend --> User1: Return notification data


@enduml