@startuml Get notification status
skinparam shadowing true
skinparam sequence {
	ParticipantBackgroundColor LightYellow
	ParticipantBorderColor red
}
Title: Get notification status
actor "Admin" as User1
participant "Backoffice" as Frontend
participant "Microservice" as Microservice
participant "MSSQL" as Database

User1 -> Frontend: Get notification all status

Frontend -> Microservice: GET /notification/status

Microservice -> Database: Get notification all status

alt Success

Database --> Microservice: Return notification all status

Microservice --> Frontend: Return notification all status

Frontend --> User1: Return notification all status

else #LightYellow

Database --> Microservice: Return error

Microservice --> Frontend: Return error

Frontend --> User1: Return error

end

@enduml