@startuml User delete notification token from database
skinparam shadowing true
skinparam sequence {
	ParticipantBackgroundColor LightYellow
	ParticipantBorderColor red
}
Title: User delete notification token from database
actor "User" as User1
participant "Frontend" as Frontend
participant "Microservice" as Microservice
participant "MSSQL" as Database

User1 -> Frontend: When user \nlogout from application

Frontend -> Microservice: (DELETE /user-notification-token/{empID}/{token}) \nSend device uuid to microservice

Microservice -> Database: Delete device uuid from database

alt success 

Microservice <-- Database: Return success

Frontend <-- Microservice: Return success

User1 <-- Frontend: Return success

else #LightYellow

Microservice <-- Database: Return fail

Frontend <-- Microservice: Return fail

User1 <-- Frontend: Return fail

end

@enduml