@startuml User on/off push notification
skinparam shadowing true
skinparam sequence {
	ParticipantBackgroundColor LightYellow
	ParticipantBorderColor red
}
Title: User on/off push notification
actor "User" as User1
participant "Frontend" as Frontend
participant "Microservice" as Microservice
participant "MSSQL" as Database

User1 -> Frontend: On/Off push notification

Frontend -> Microservice: PUT /v1/user/push-notification

Microservice -> Database: Save user push notification on/off

alt Success

Microservice <-- Database: Return success

Frontend <-- Microservice: Return success

User1 <-- Frontend: Return success

else #LightYellow

Microservice <-- Database: Return error

Frontend <-- Microservice: Return error

User1 <-- Frontend: Return error

end

@enduml