@startuml User Delete Inbox Message
skinparam shadowing true
skinparam sequence {
	ParticipantBackgroundColor LightYellow
	ParticipantBorderColor red
}
Title: User Delete Inbox Message
actor "User" as User1
participant "Frontend" as Frontend
participant "Microservice" as Microservice
participant "MSSQL" as Database

User1 -> Frontend: Click on Inbox

Frontend -> Microservice: DELETE /v1/user/inbox/:id

Microservice -> Database: Delete inbox message id

alt Success

Microservice <-- Database: Return Success

Frontend <-- Microservice: Return Success

User1 <-- Frontend: Return Success

else #LightYellow

Microservice <-- Database: Return Error

Frontend <-- Microservice: Return Error

User1 <-- Frontend: Return Error

end

@enduml