@startuml Delete File
skinparam shadowing true
skinparam sequence {
	ParticipantBackgroundColor LightYellow
	ParticipantBorderColor red
}
Title: Delete File
actor "Admin" as User1
participant "Backoffice" as Frontend
participant "Microservice" as Microservice
participant "Minio" as S3
participant "MSSQL" as Database

User1 -> Frontend: Delete file from content

Frontend -> Microservice: DELETE /file/{id}

Microservice -> S3: Delete file from minio

alt Delete success
	S3 --> Microservice: Return success
	Microservice -> Database: Delete file from database

	alt Success
	Database --> Microservice: Return success

	Frontend <-- Microservice: Return success

	User1 <-- Frontend: Return success
	else #LightYellow

	Database --> Microservice: Return error

	Frontend <-- Microservice: Return error

	User1 <-- Frontend: Return error
	end
else #LightYellow
	S3 --> Microservice: Return error
	Microservice --> Frontend: Return error
	User1 <-- Frontend: Return error
end


@enduml