@startuml Admin Delete File
skinparam shadowing true
skinparam sequence {
	ParticipantBackgroundColor LightYellow
	ParticipantBorderColor red
}
Title: Admin Delete File
actor "Admin" as User1
participant "Backoffice" as Frontend
participant "Microservice" as Microservice
participant "S3" as S3
participant "MSSQL" as Database

User1 -> Frontend: List Files

Frontend -> Microservice: DELETE /v1/files/:id

Microservice -> Database: Delete files from database

alt Success
	Database --> Microservice: Return success

	Microservice -> S3: Delete files from S3

	alt Success

	S3 --> Microservice: Return success

	Microservice --> Frontend: Return success

	Frontend --> User1: Return success

	else #LightYellow

	S3 --> Microservice: Return error

	Microservice --> Microservice: Rollback Database

	Microservice --> Frontend: Return error

	Frontend --> User1: Return error

	end
else #LightYellow
	Database --> Microservice: Return error

	Microservice --> Frontend: Return error

	Frontend --> User1: Return error
end


@enduml