@startuml Delete Banner
skinparam shadowing true
skinparam sequence {
	ParticipantBackgroundColor LightYellow
	ParticipantBorderColor red
}
Title: Delete Banner
actor "Admin" as User1
participant "Backoffice" as Frontend
participant "Microservice" as Microservice
participant "MSSQL" as Database

User1 -> Frontend: Delete banner data

Frontend -> Microservice: DELETE /v1/banner/{id}

Microservice -> Database: Delete banner data

alt success

Database --> Microservice: Return success

Microservice --> Frontend: Return success

Frontend --> User1: Return success

else #LightYellow

Database --> Microservice: Return error

Microservice --> Frontend: Return error

Frontend --> User1: Return error

end

@enduml