@startuml Admin Update Upload File
skinparam shadowing true
skinparam sequence {
	ParticipantBackgroundColor LightYellow
	ParticipantBorderColor red
}
Title: Admin Update Upload File
actor "Admin" as User1
participant "Backoffice" as Frontend
participant "Microservice" as Microservice
participant "S3" as S3
participant "MSSQL" as Database

User1 -> Frontend: Select image to upload

Frontend -> Microservice: PUT /v1/upload/:id

Microservice -> S3: Upload image to S3

alt Upload success
	S3 --> Microservice: Return image URL
	Microservice -> Database: Update image url to files table

	alt Update success
		Database --> Microservice: Return success
		Microservice --> Frontend: Return success
		User1 <-- Frontend: Return success
	else #LightYellow
		Database --> Microservice: Return error
		Microservice --> Frontend: Return error
		User1 <-- Frontend: Return error
	end
else #LightYellow
	S3 --> Microservice: Return error
	Microservice --> Frontend: Return error
	User1 <-- Frontend: Return error
end


@enduml