@startuml Get Banner
skinparam shadowing true
skinparam sequence {
	ParticipantBackgroundColor LightYellow
	ParticipantBorderColor red
}
Title: Get Banner
actor "Admin" as User1
participant "Backoffice" as Frontend
participant "Microservice" as Microservice
participant "MSSQL" as Database

User1 -> Frontend: Get banner by id

Frontend -> Microservice: GET /v1/banner/{id}

Microservice -> Database: Get banner data

alt Success

Database --> Microservice: Return banner data

Microservice --> Frontend: Return banner data

Frontend --> User1: Return banner data

else #LightYellow

Database --> Microservice: Return error

Microservice --> Frontend: Return error

Frontend --> User1: Return error

end

@enduml